In [2]:
import numpy as np

In [3]:
#create an array
a=np.array([23,23,23,23,23,4,2,4,4])

In [4]:
print(a)
# arrays are of type np.ndarray
print(type(a))
print(a.shape)

[23 23 23 23 23  4  2  4  4]
<class 'numpy.ndarray'>
(9,)


In [6]:
b=np.array([[1],[2],[3],[4]])
b.shape

(4, 1)

In [10]:
b[0,0]

1

In [11]:
b[0][0]

1

In [13]:
#create zeros ones
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
c=np.full((4,2),34)
c

array([[34, 34],
       [34, 34],
       [34, 34],
       [34, 34]])

In [21]:
# identity matrix
d=np.eye(5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
# random array
randommatrix=np.random.random((3,4))
randommatrix

array([[0.14559108, 0.15886643, 0.25825092, 0.72340295],
       [0.37879538, 0.60663462, 0.00316624, 0.87799805],
       [0.37126561, 0.68549856, 0.06580782, 0.43782824]])

In [30]:
print(randommatrix[:,1]) # row then  column
print(randommatrix[:][1]) # column then row 

[0.15886643 0.60663462 0.68549856]
[0.37879538 0.60663462 0.00316624 0.87799805]


In [32]:
z=np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
z[:,-1]=12 # slicing
z

array([[ 0.,  0., 12.],
       [ 0.,  0., 12.],
       [ 0.,  0., 12.]])

In [34]:
# datatypes

In [35]:
z.dtype

dtype('float64')

In [37]:
t=np.array([23,1,23,23,234,4,],dtype=np.float16)
t

array([ 23.,   1.,  23.,  23., 234.,   4.], dtype=float16)

In [41]:
# mathematical operations
x=np.array([[1,2],[3,4]])
y=np.array([[1,1],[1,1]])

print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))


[[2 3]
 [4 5]]
[[2 3]
 [4 5]]
[[0 1]
 [2 3]]
[[0 1]
 [2 3]]


In [45]:
# multiplication elementwise
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1. 2.]
 [3. 4.]]
[[1. 2.]
 [3. 4.]]


In [49]:
# matrix multiplication and dot products
print(x.dot(y))
print(np.dot(x,y))
print(np.matmul(x,y))

[[3 3]
 [7 7]]
[[3 3]
 [7 7]]
[[3 3]
 [7 7]]


In [65]:
#multiplication of vecors dot product
a=np.array([1,2,3,4])
print(a)
b=np.array([1,2,3,4])
print(b)
print(a.dot(b)) # transpose of the first vector multiplied by second vector


[1 2 3 4]
[1 2 3 4]
30


In [55]:
# summation
print(a)
print(sum(a))
print(np.sum(a))


[1 2 3 4]
10
10


In [60]:
print(x)
print(np.sum(x))
print("vertical",np.sum(x,axis=0))
print("horizontal",np.sum(x,axis=1))

[[1 2]
 [3 4]]
10
vertical [4 6]
horizontal [3 7]


In [68]:
# stacking of arrays
print(a)
b=b**3
print(b)
print('stack along horizontal\n',np.stack((a,b),axis=1))


[1 2 3 4]
[         1  134217728 2030534587          0]
stack along horizontal
 [[         1          1]
 [         2  134217728]
 [         3 2030534587]
 [         4          0]]


In [80]:
# reshape a numpy array
print(a)
print(a.reshape((4,1)))
print(a.reshape((4,)))
print(a.reshape((2,-1)))
print(a.reshape((-1,2)))

[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]
[1 2 3 4]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
