In [ ]:
#numpy function to convert (3,3) to (9,)
# flatten()

# stacks oned array to  columns of 2d array col_stack()

#the function modifies the array itself whereas the function returns a new array
# resize and reshape
# copyto() copy() view() gives the same result
# convert to list np.tolist(a)
# np.size(a) finds the number of elements in the array


In [1]:
import numpy as np

In [2]:
a=np.random.randint(0,15,(4,4))
a

array([[ 3, 10, 12,  1],
       [ 2,  7,  7, 13],
       [14,  8,  6, 10],
       [11,  5,  4, 13]])

In [15]:
a[(a>=5) & (a<=10)]


array([10,  7,  7,  8,  6, 10,  5])

In [17]:
a.reshape(2,8)

array([[ 3, 10, 12,  1,  2,  7,  7, 13],
       [14,  8,  6, 10, 11,  5,  4, 13]])