In [1]:
import numpy as np

In [2]:

a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#numpy random module
np.random.shuffle(a)
a

array([0, 8, 1, 5, 9, 4, 6, 3, 2, 7])

In [6]:
np.random.rand(3,3)

array([[0.14813123, 0.98656753, 0.25858041],
       [0.18109957, 0.72844105, 0.36512728],
       [0.5814254 , 0.34239688, 0.48357536]])

In [10]:
np.random.randn(2,3) # retrun from standard normal distribution

array([[-1.74312125,  0.81477024, -0.77780628],
       [ 1.7181313 ,  0.04942713, -0.36997659]])

In [12]:
a=np.random.randint(1,10,4)
a

array([3, 7, 8, 9])

In [15]:
element=np.random.choice([1,2,3,4,5,90])
element

2

In [29]:
np.random.seed(42)
np.random.rand(2,3)

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452]])

In [ ]:
# rand->random values in a given shape
# randn->return a sample from standard normal distribution
# randint-> return random integers from low to high(exclusive)
#random->return random floats int half open interval (0.0,1.0]
#choice ->generates a random sample from a given 1d array
#shuffle -> shuffles the contents of a sequence