# some more numpy functions 

min,max
mean
median
average
variance
standard deviation

In [1]:
import numpy as np

In [5]:
a=np.array([[1,2,3,4],[8,9,1,0]])
print(a)
print(np.min(a))
print(np.min(a,axis=0)) # vertical axis
print(np.max(a,axis=1)) # horizontal axis

[[1 2 3 4]
 [8 9 1 0]]
0
[1 2 1 0]
[4 9]


In [9]:
b=np.array([[1,2,3,4],[8,9,1,0]])
print(b)
mean=np.mean(b)
print(mean)

print(np.mean(b,axis=0)) # vertical axis
print(np.mean(b,axis=1)) # horizontal axis


[[1 2 3 4]
 [8 9 1 0]]
3.5
[4.5 5.5 2.  2. ]
[2.5 4.5]


In [16]:
c=np.array([1,2,3,4,6])
print(c)
print(np.median(c)) 
# median is n+1/2 when n is even
# median is n/2 when n is odd

[1 2 3 4 6]
3.0


In [17]:
# mean vs average (weighted)
w=np.array([1,2,3,4,6])

print(np.average(c,weights=w))# weights multiply to corresponding values

4.125


In [21]:
# standard deviation
# sigma=sqrt(sum((x-mean)^2)/n)
# variance=sum((x-mean)^2)/n
# standard deviation is the square root of variance


print(np.std(c))
print('variance',np.var(c))

1.7204650534085253
variance 2.96
